### PR TITLE
fix clipping issue on abnormal size icons

### LINKED ISSUE #19: provide an option to decouple fontSize & canvasSize
Hi fellows,

First, thanks for this useful lib!

It would be very useful if an option like `options.font.size` or something is provided to use as font size while rendering text, as sometimes `font-size` and the actual dimensions of the rendered text on the canvas are quite different (and would be clipped if the actual size is bigger). please see the example [here](https://jsfiddle.net/qgrrv2s2/)

so an optional option is really helpful as users can tweak it by themselve if meet such scenario.

I'd love to provide a PR if you like

Thanks

### PR DESCRIPTION
**Pull request by jcppman**
if the icon is too wide/tall, it wil be clipped. The new approach of
finding dimensions is measuring the actual rendered icon.

closes #19

### CODE REVIEW

**Comment by jcppman** [comment]
hmm weird failure:

```
The command "eval git clone --depth=50 https://github.com/jwarby/jquery-awesome-cursor.git jwarby/jquery-awesome-cursor" failed 3 times.
```

**Comment by jwarby** [comment]
Thanks for the pull request @jcppman.  My guess for the CI failure is that it's a permissions thing, probably only my account has the relevant permissions.

I'll try and take a look at the branch tonight and see if I can fix the tests (not CI).  Most likely won't have time tonight though, so will probably be tomorrow instead.

Thanks again!

**Comment by jwarby** [comment]
The single test failure was simply because you've fixed the clipping issue and one of the "expected" output images was clipped! (`test/expected/black-desktop-22.png`).

I've updated the expected image for that test in a local copy of your branch, and the tests are all passing now :).  I still want to add a few more tests that would fail without your fix, check it in Firefox, and actually take look at the diff before I get in merged in.

Thanks again!

**Comment by jcppman** [comment]
Cool, good to know that it works :)

**Pull request merged**
